### ISSUE TITLE
build nginx support files after installing passenger

### ISSUE THREAD

**Issue by jurek7** [chef-cookbooks/nginx#233]
passenger needs to build some support files and it can be done during first passenger initialization but it's impossible(permissions) and should be done manually(by root) If you install nginx and passenger as root and start it as another(non root) user, in my case "deploy" user

following script would help(after installing passenger):

``` bash
cd `passenger-config --root` && rake nginx
```

**Comment by mmahalwy** [comment]
passenger-install-nginx-module ?

**Comment by rmoriz** [comment]
IMHO invalid.

`passenger-config` just adds something to nginx.conf according to https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#inserting_passenger_root_for_apt

**Comment by iennae** [comment]
Closing this based on @rmoriz comments. If this is something that should be revisited please reopen with additional information including answers to the questions earlier in the thread.
