### ISSUE TITLE
CentOS/RHEL 7 use systemd for process control

### ISSUE THREAD

**Issue by miketheman** [chef-cookbooks/nginx#271]
Converge fails on enabling/starting the process when using nginx 1.6.1 from EPEL.

``` console
[kitchen@4df4899d76f0 ~]$ rpm -ql nginx | grep init
[kitchen@4df4899d76f0 ~]$ rpm -ql nginx | grep service
/usr/lib/systemd/system/nginx.service
```

One solution may be to factor out the `service` declaration to it's own recipe and switch on all the platform versions and oddities over there, and accept notifications from other recipes.

Caveat: this still seems to be a blocker for docker (see what I did there?). docker container for cetnos7 uses fakesystemd-1-15.el7.centos.noarch - so systemctl isn't installed, therefore may be unavailable.

**Comment by rmoriz** [comment]
:+1: This is important, as Debian 8 uses systemd, too. Will look into it.

**Comment by tas50** [comment]
Thanks for opening this issue. Just today we merged the changes from the chef_nginx fork of this cookbook back to master here. It’s a pretty huge change set and includes over a year of active development that resulted in several major releases. I think there’s a very high chance that this issue has been resolved with that work and at this point I’m going to close this issue out. I’d encourage you to checkout the master branch and please open this issue back up if you’re still having the problem there.

Here’s the changes that were just merged in: https://github.com/chef-cookbooks/nginx/pull/435
