### ISSUE TITLE
'enable' fails on OSX

### ISSUE THREAD

**Issue by rgormley** [chef-cookbooks/nginx#272]
I know OS X is not an officially supported platform, but we have had some success in the past. However, with 2.7.4 on OS X 10.9.4, we get the following error:

```
Recipe: nginx::package
  * package[nginx] action install (skipped due to not_if)
  * service[nginx] action enable
    * Could not find service's label in plist file ''!
================================================================================
Error executing action `enable` on resource 'service[nginx]'
================================================================================
```

http://pastebin.com/jCYHVFsx

**Comment by rmoriz** [comment]
Did you find a solution? Do you mind creating a PR?

**Comment by rgormley** [comment]
Unfortunately I haven't touched this since.

**Comment by rmoriz** [comment]
Do you remember which Chef version/osx package provider you've used back then?

**Comment by rgormley** [comment]
It was the default cookbook (https://supermarket.chef.io/cookbooks/nginx) and I believe around 11.14-11.16?

**Comment by rmoriz** [comment]
With Chef 12  homebrew became the default package provider for OS X. I'm not sure if this will change anything regarding the service-issue. Just to gather information.

**Comment by iennae** [comment]
Hey folks,

macOS isn't a supported platform at this time. We welcome PRs to add the functionality. As this is an older issue I'm going to go ahead and close.

**Comment by alex-w-k** [comment]
Sorry to reply to an older issue, but how would you expect to see macOS support be brought to this cookbook, through a homebrew package or compiling from source?

**Comment by rmoriz** [comment]
@alex-w-k The cookbook (the configuration part) might still work on macOS if you just install nginx using brew upfront, see https://github.com/chef-cookbooks/nginx#package-installation-using-distro-repositories - I've never seen anyone seriously managing self-compiled nginxes on macOS, everyone goes with brew (some oldskool users with macports).
