### ISSUE TITLE
Fails to install on freebsd with [nginx::source] ---> needs libpcre

### ISSUE THREAD

**Issue by mike-pt** [chef-cookbooks/nginx#274]
```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '69'
---- Begin output of pkg rquery '%v' libpcre3 ----
STDOUT: 
STDERR: 
---- End output of pkg rquery '%v' libpcre3 ----
Ran pkg rquery '%v' libpcre3 returned 69

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/nginx/recipes/source.rb

  3: package "libpcre3"
  4: package "libpcre3-dev"

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/nginx/recipes/source.rb:3:in `from_file'

freebsd_package("libpcre3") do
  provider Chef::Provider::Package::Freebsd::Pkgng
  action :install
  retries 0
  retry_delay 2
  guard_interpreter :default
  package_name "libpcre3"
  timeout 900
  created_as_type :package
  cookbook_name "nginx"
  recipe_name "source"
end
```

NOTE: in freebsd the package name is "pcre"

% pkg rquery '%v %n' pcre
% 8.35 pcre

**Comment by tas50** [comment]
Thanks for opening this issue. Just today we merged the changes from the chef_nginx fork of this cookbook back to master here. It’s a pretty huge change set and includes over a year of active development that resulted in several major releases. I think there’s a very high chance that this issue has been resolved with that work and at this point I’m going to close this issue out. I’d encourage you to checkout the master branch and please open this issue back up if you’re still having the problem there.

Here’s the changes that were just merged in: https://github.com/chef-cookbooks/nginx/pull/435
