### ISSUE TITLE
Please add support for FreeBSD 10 pkg install

### ISSUE THREAD

**Issue by mike-pt** [chef-cookbooks/nginx#275]
At the moment the package install assumes that the apt repo needs to be added.

How hard would it be to add freebsd pkgng support?

**Comment by rmoriz** [comment]
Did you manage it? Would you mind providing a PR?

**Comment by mike-pt** [comment]
Nope, got busy with other stuff, acctually seting up a reciepe now for ubuntu, but I can certainly have a look and try ;)

**Comment by tas50** [comment]
Thanks for opening this issue. Just today we merged the changes from the chef_nginx fork of this cookbook back to master here. It’s a pretty huge change set and includes over a year of active development that resulted in several major releases. I think there’s a very high chance that this issue has been resolved with that work and at this point I’m going to close this issue out. I’d encourage you to checkout the master branch and please open this issue back up if you’re still having the problem there.

Here’s the changes that were just merged in: https://github.com/chef-cookbooks/nginx/pull/435
