### ISSUE TITLE
unknown directive "passenger_root" in /etc/nginx/conf.d/passenger.conf

### ISSUE THREAD

**Issue by mmahalwy** [chef-cookbooks/nginx#320]
How can I rid of this issue for passenger?

**Comment by rmoriz** [comment]
Looks like Passenger is not installed correctly. Do you need it? If not, delete the passenger.conf. If you need it, try to find out, why it doesn't get build.

**Comment by rmoriz** [comment]
Also: What does `nginx -v` show?

**Comment by tas50** [comment]
Thanks for opening this issue. Just today we merged the changes from the chef_nginx fork of this cookbook back to master here. It’s a pretty huge change set and includes over a year of active development that resulted in several major releases. I think there’s a very high chance that this issue has been resolved with that work and at this point I’m going to close this issue out. I’d encourage you to checkout the master branch and please open this issue back up if you’re still having the problem there.

Here’s the changes that were just merged in: https://github.com/chef-cookbooks/nginx/pull/435
