### ISSUE TITLE
Passenger gem is rebuilt on chef runs.

### ISSUE THREAD

**Issue by Aslan** [chef-cookbooks/nginx#343]
I have had a major (so far transient) problem with this cookbook. The goal is to install nginx with passenger by building everything from source. This will mean nginx has to compile with passenger. 
this installation works fine at the beginning and passenger is installed. when it works there are 3447 files under the passenger gem:
find /usr/local/lib/ruby/gems/2.1.0/gems/passenger-4.0.59 | wc -l  
3447
but after couple of chef runs i see passenger is not working 
➜  cornice_frontend  passenger-status  
ERROR: Phusion Passenger doesn't seem to be running.

and after a lot of investigation i noticed PassengerWatchdog is missing. 
➜  passenger-4.0.59  locate PassengerWatchdog
➜
when the passenger watchdog is not there passenger wouldn't work
and
➜  passenger-4.0.59  find /usr/local/lib/ruby/gems/2.1.0/gems/passenger-4.0.59 | wc -l  
3349
which shows some of the files are not there any more. 

when passenger is properly installed:
➜  passenger-4.0.59  locate PassengerWatchdog
/usr/local/lib/ruby/gems/2.1.0/gems/passenger-4.0.59/buildout/agents/PassengerWatchdog
/usr/local/lib/ruby/gems/2.1.0/gems/passenger-4.0.59/buildout/agents/PassengerWatchdog.o 

These all lead to the fact that the gem has been reinstalled! the time stamp of the gem files confirms this. I dont know what is causing the gem to be reinstalled. I am using the cookbook out of the box with no modifications. not even a wrapper cookbook. all i have done was to set the attributes for install method and few other passenger.conf stuff.

**Comment by rmoriz** [comment]
Distro? Version? Run List? Attributes?

**Comment by tas50** [comment]
Thanks for opening this issue. Just today we merged the changes from the chef_nginx fork of this cookbook back to master here. It’s a pretty huge change set and includes over a year of active development that resulted in several major releases. I think there’s a very high chance that this issue has been resolved with that work and at this point I’m going to close this issue out. I’d encourage you to checkout the master branch and please open this issue back up if you’re still having the problem there.

Here’s the changes that were just merged in: https://github.com/chef-cookbooks/nginx/pull/435
