### ISSUE TITLE
3.0 Rewrite Suggestions

### ISSUE THREAD

**Issue by sauliusgrigaitis** [chef-cookbooks/nginx#348]
I would like to have list of 3.0 rewrite suggestions, so during refactoring some of those suggestions could be considered and implemented.

**Comment by sauliusgrigaitis** [comment]
I suggest to add option to use Phusion Passenger distribution of Nginx https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#installation . Passenger is getting really popular and those Phusion packages are really nice way to get Nginx & Passenger installed. I prefer Phusion Passenger packages because:

* It's easier to install and update Passenger
* It's possible to get automated Passenger security updates via unattended-upgrades
* Avoids Passenger compilation and all the problems that come with it
* I use it in production for more than a year and I don't see any reason to switch back to Passenger compilation.

I did quick port to Phusion packages some time ago https://github.com/necolt/nginx/ , it gives basic idea how easy it is to switch to Phusion distribution.

**Comment by iennae** [comment]
The change to using the phusion passenger distribution looks like it was implemented. Please reopen with additional details if necessary.
