### ISSUE TITLE
Issue with pagespeed module

### ISSUE THREAD

**Issue by thomascooper** [chef-cookbooks/nginx#357]
Team,

I have a pre-functioning cookbook using the most current version of the nginx cookbook, using the default recipe. I have had no issues, when I needed to add the status module, after adding the following it worked:

include_recipe 'nginx::default'
include_recipe 'nginx::http_stub_status_module'

But when I needed the pagespeed module, I added the following (right below the above lines):

include_recipe 'nginx::pagespeed_module'

No matter what I do after updating the server, adding 'pagespeed on' to any vhost, gives a pagespeed is not a a valid method error. Here is the output of nginx -V:

nginx version: nginx/1.2.1
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-log-path=/var/log/nginx/access.log --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --with-pcre-jit --with-debug --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_realip_module --with-http_stub_status_module --with-http_ssl_module --with-http_sub_module --with-http_xslt_module --with-ipv6 --with-sha1=/usr/include/openssl --with-md5=/usr/include/openssl --with-mail --with-mail_ssl_module --add-module=/tmp/buildd/nginx-1.2.1/debian/modules/nginx-auth-pam --add-module=/tmp/buildd/nginx-1.2.1/debian/modules/nginx-echo --add-module=/tmp/buildd/nginx-1.2.1/debian/modules/nginx-upstream-fair --add-module=/tmp/buildd/nginx-1.2.1/debian/modules/nginx-dav-ext-module

So it looks like pagespeed was not included in the build...

Any advice?

Thanks,
Tom

**Comment by rmoriz** [comment]
Distro? Version? Attributes?

nginx 1.2.1 was release 3 years ago btw.

**Comment by tas50** [comment]
Thanks for opening this issue. Just today we merged the changes from the chef_nginx fork of this cookbook back to master here. It’s a pretty huge change set and includes over a year of active development that resulted in several major releases. I think there’s a very high chance that this issue has been resolved with that work and at this point I’m going to close this issue out. I’d encourage you to checkout the master branch and please open this issue back up if you’re still having the problem there.

Here’s the changes that were just merged in: https://github.com/chef-cookbooks/nginx/pull/435
