### ISSUE TITLE
Anything chef-brigade can do to help?

### ISSUE THREAD

**Issue by josephholsten** [chef-cookbooks/nginx#368]
Is there anything @chef-brigade can do to help out? We're probably going to start using this in our infra, so we want to keep it awesome.

If you need any administrative help, want a slack channel, website, testing infra &c, just let us know. It doesn't need to have the brigade name anywhere on it.

**Comment by miketheman** [comment]
Hi! https://github.com/miketheman/nginx#read-this-first Should explain the desired future of this cookbook.

**Comment by josephholsten** [comment]
@miketheman would it be useful for us to work off master while that's in progress? Or is the new stuff going into the `3.0.0-rewrite` branch?

**Comment by miketheman** [comment]
New goes into 3.0.0 branch. master is something I'd like to abandon - the congnitive load of maintenance is pretty high, and previous maintainers (reset, someara) and I met and decided it's better to cut this loose.

**Comment by josephholsten** [comment]
is `3.0.0-rewrite` "usable"? would you accept PRs against it?

**Comment by miketheman** [comment]
Most certainly. The goal is to make it resource-heavy awesomeness. I'm almost ready to ship a test-kitchen automated suite as well.

**Comment by acaiafa** [comment]
Should just take a look at 

https://github.com/bloomberg/nginx-cookbook

its very reusable.

**Comment by acaiafa** [comment]
@josephholsten

**Comment by acaiafa** [comment]
@miketheman whats your thoughts around this? We can overwrite the current cookbook and push this one out.

**Comment by miketheman** [comment]
@acaiafa I feel that there's some good ideas in the cookbook you're proposing, but it relies heavily on the `poise` approach - something that is still pretty new in the approach.
Have you looked at the 3.0.0-rewrite branch here? There is already ongoing effort to rewrite and improve the current cookbook without reliance on many external resources, as well as providing a simple platform for use.

As mentioned above, any PRs to the 3.0.0 will be considered, as I've only had time to work on debian/ubuntu derivatives, and would like to get rhel/centos supported before release.

**Comment by acaiafa** [comment]
@miketheman yeah i mean poise is just a helpful dependency for workflow. I can easily pull out poise its not a hard dependency. It however removes alot of the additional code people would have to write. I have seen the 3.0 rewrite branch and its still being written in a very similar manor as the current one. 

  Again up to you guys to continue to work on this but mine is already working.

**Comment by tas50** [comment]
Closing this one out since we have dedicated resources on the cookbook now, but Sous Chefs help is always appreciated
