### ISSUE TITLE
Unable to bind address when using repo

### ISSUE THREAD

**Issue by jshthornton** [chef-cookbooks/nginx#375]
I am using the repo version so my run list is[ nginx::repo, nginx::default] but it results in:
`STDERR: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)` from `recipes/default.rb:24`

**Comment by lylianmeyemezu** [comment]
Hi,
same issue.
does anyone have a workaround ?
regards

**Comment by stekershaw** [comment]
I've just run into this on Ubuntu 14.04 with the nginx repo install. Everything would install OK but when run again I would get the bind error.

The problem for me was to do with the service definition and pid files.

I found that changing the pidfile location fixed it for me. I have this in my recipe:
```
# Install nginx from the nginx repo
node.default['nginx']['repo_source'] = 'nginx'
# Tell nginx to use the pid file that that the Ubuntu 14.04 nginx repo defines in the init.d file
node.default['nginx']['pid'] = '/var/run/nginx.pid'

include_recipe 'nginx::default'
```

I think it's kind-of related to https://github.com/miketheman/nginx/issues/248

**Comment by ArturT** [comment]
@stekershaw Thanks for help. There is related PR https://github.com/miketheman/nginx/pull/223/files which was merged and that's a bit weird because I'm using ubuntu-14.04.3-server-amd64 and `/var/run/nginx.pid` works instead of `/run/nginx.pid`.

**Comment by iennae** [comment]
Can you check the current release of the cookbook to see if you are still having this problem? There have been a number of updates that have been merged in recently. Please reopen if you are still seeing this problem.
