### ISSUE TITLE
nginx 1.8 loses pid upon nginx conf change

### ISSUE THREAD

**Issue by jshthornton** [chef-cookbooks/nginx#377]
When using the repo (1.8) package install on ubuntu 14.04 the pid location is changed from `/var/run/nginx.pid` to `/run/nginx.pid`. This causes nginx to delete it's current pid file and not replace it.

**Comment by StyleT** [comment]
Same issue here. Is there a workaround?

**Comment by jshthornton** [comment]
@StyleT I just changed the node attribute of the pid location to be what nginx uses by default for the distro.

**Comment by StyleT** [comment]
@jshthornton still not working on Ubuntu 14.04.01 with package install. Right after provision `sudo service nginx status` returns `nginx is not running` and this is not true :(

**Comment by sean-kang** [comment]
I had the same problem in Ubuntu 14.04 when I used repo and default recipes to set up nginx from nginx.org repository. PID file was deleted although nginx service was running. I fixed the problem by overriding pid attribute as @jshthornton suggested. For example, I added the following attribute to our wrapper cookbook to override pid attribute defined in attribute/default.rb in nginx cookbook. 

default['nginx']['pid'] = '/var/run/nginx.pid'

**Comment by tas50** [comment]
Thanks for opening this issue. Just today we merged the changes from the chef_nginx fork of this cookbook back to master here. It’s a pretty huge change set and includes over a year of active development that resulted in several major releases. I think there’s a very high chance that this issue has been resolved with that work and at this point I’m going to close this issue out. I’d encourage you to checkout the master branch and please open this issue back up if you’re still having the problem there.

Here’s the changes that were just merged in: https://github.com/chef-cookbooks/nginx/pull/435
