### ISSUE TITLE
2.7.6 doesn't work on rhel 7

### ISSUE THREAD

**Issue by ZepedaMcMillan** [chef-cookbooks/nginx#381]
There is no ruby-devel package available in rhel7, causing the passenger install to fail. Perhaps adding conditionality to the package installation so that you can disable it by default. We're compiling ruby during our AMI baking process in AWS, so libcurl-devel is already installed along with ruby. Installing ruby-devel shouldn't be necessary at that point.

**Comment by tas50** [comment]
Thanks for opening this issue. Just today we merged the changes from the chef_nginx fork of this cookbook back to master here. It’s a pretty huge change set and includes over a year of active development that resulted in several major releases. I think there’s a very high chance that this issue has been resolved with that work and at this point I’m going to close this issue out. I’d encourage you to checkout the master branch and please open this issue back up if you’re still having the problem there.

Here’s the changes that were just merged in: https://github.com/chef-cookbooks/nginx/pull/435
