### ISSUE TITLE
pin on apt version 2.6.1

### ISSUE THREAD

**Issue by cyberflow** [chef-cookbooks/nginx#393]
Hello,

What reason to pin apt cookbook version on 2.6.1? it's conflict with cookbooks which use apt version >2.7 for https repository.

**Comment by miketheman** [comment]
@cyberflow The current metadata.rb uses `suggests`, not `depends` - are you seeing a conflict when using this?

**Comment by tas50** [comment]
#422 removes the version constraint on apt and resolves this

**Comment by tas50** [comment]
This particular issue has been pulled into the chef_nginx cookbook 2.8.0 release. The chef_nginx cookbook is a fork of this cookbook with many of the outstanding issues in the 2.7.6 release resolved. The release is backwards compatible with this cookbook outside of the name change, which obviously requires updating runlist and and metadata dependencies. I'd highly suggest giving it a try to see if this resolves you nginx cookbook woes.

https://github.com/chef-cookbooks/chef_nginx
https://supermarket.chef.io/cookbooks/chef_nginx#changelog

**Comment by tas50** [comment]
Thanks for opening this issue. Just today we merged the changes from the chef_nginx fork of this cookbook back to master here. It’s a pretty huge change set and includes over a year of active development that resulted in several major releases. I think there’s a very high chance that this issue has been resolved with that work and at this point I’m going to close this issue out. I’d encourage you to checkout the master branch and please open this issue back up if you’re still having the problem there.

Here’s the changes that were just merged in: https://github.com/chef-cookbooks/nginx/pull/435
