### ISSUE TITLE
Incompatibility with Chef Server 11

### ISSUE THREAD

**Issue by mmiranda** [chef-cookbooks/nginx#398]
As Nginx recipe depends Bluepill which depends Rsyslog which depends Compat Resource...

we can say that nginx recipe doesn't support Chef 11 anymore. I think that would be a good idea to put that on requisites.

https://github.com/chef-cookbooks/rsyslog/commit/c696b7d28b568bf9cf63323735199b3c0db55cff

**Comment by hrak** [comment]
The 2.7.x branch is working fine for me on Chef 11 using bluepill 2.3.1 & rsyslog 2.2.0.
bluepill >= 2.4.0 and rsyslog >= 3.0.0 is Chef 12 only.

**Comment by tas50** [comment]
If you pin to the older releases in your environment you can still use Chef client 11. I'd highly recommend the upgrade though as there are huge fixes from the last few years in Chef 12 and the newer cookbooks it allows you to use.

**Comment by tas50** [comment]
Thanks for opening this issue. Just today we merged the changes from the chef_nginx fork of this cookbook back to master here. It’s a pretty huge change set and includes over a year of active development that resulted in several major releases. I think there’s a very high chance that this issue has been resolved with that work and at this point I’m going to close this issue out. I’d encourage you to checkout the master branch and please open this issue back up if you’re still having the problem there.

Here’s the changes that were just merged in: https://github.com/chef-cookbooks/nginx/pull/435
