### ISSUE TITLE
Add ability to configure and deploy reasonably complete "server" from template

### ISSUE THREAD

**Issue by nkadel-skyhook** [chef-cookbooks/nginx#400]
Since the cookbook does not actually provide hooks to configure and deploy a well formed "/etc/nginx/sites-available/[server] from options, it means that most sysadmins have to write their own customized cookbooks to wrap the LWRP's in nginx to deploy and activate their hand-constructed templates or config files.

May I suggest providing a recipe to read a hash that describes such a "server" from a role or other recipe? I'm working on such a recipe now for SSL enabled load balancer configurations and would be happy to work with you to make it available in the nginx cookbook.

**Comment by miketheman** [comment]
@nkadel-skyhook I think I understand what you're saying, but the opinion of this cookbook is to be a building block, not an end-all cookbook - this style got us into trouble the first time around.

Considering that the way to control nginx sites and configuration is via an nginx config file, I do not see how putting data into node attributes/hashes/etc is any better than allowing a user to use this building block, and supply their own config file (template, cookbook_file, etc) similar to the [working approach shown in the example recipe](https://github.com/miketheman/nginx/blob/3.0.0-rewrite/recipes/example.rb#L20-L35).

Can you explain why using a hash (which can have confusing behaviors when using node attributes and precedence levels) is better than leaving the common interface to a file that the end user controls explicitly?

**Comment by nkadel-skyhook** [comment]
I can certainly explain.  "Having a file that the end user controls explicitly" means that every single end user must devote time and effort to writing their own unique files, from scratch. This means a great deal of duplicated effort to write even the most basic and most commonly used of workable nginx configurations. A modest template and workable role could allow precisely the kind of accessible, tested, configuration access that would help make the nginx cookbook much more useful in itself. It also reduces the burden of maintaining compatible third party coookbooks which must be kept compatible with any upstream changes with the nginx cookbook itself.

I wouldn't suggest eliminating the current features, but rather an enhancement to support the most common usages. And I'd be happy to transform some of the application code I'm working with lately, for example for multiple virtual hosts behind a single Nginx instance, and offer it as a patch if that seems reasonable.

**Comment by fletchowns** [comment]
I agree with @miketheman in that this cookbook should just be a basic building block. There's so much variation in an nginx config file for a site, I don't think it's something this cookbook should be concerned with.

Nothing wrong with creating a new cookbook called nginx_site or something (in fact it looks like there are already some of these out there) whose only concern is to manage nginx site configs.

**Comment by iennae** [comment]
Based on previous responses here, it sounds the question has been answered. If not, please reopen.
