### ISSUE TITLE
Install nginx::source chef recipe without starting nginx right after installation

### ISSUE THREAD

**Issue by Blasterdick** [chef-cookbooks/nginx#406]
I need to install nginx::source chef recipe without starting nginx right after installation. How can I do it? 

Found template [sv-nginx-run.erb](https://github.com/miketheman/nginx/blob/2.7.x/templates/default/sv-nginx-run.erb), which seems to have 

`exec <%= node['nginx']['src_binary'] %> -c <%= node['nginx']['dir'] %>/nginx.conf` 

line to run nginx. 

Am I on the right way? Can I rewind it somehow with my wrapper cookbook to remove that line and get what I need?

**Comment by stevenhair** [comment]
As far as I can tell, there's no option to not restart nginx with this recipe, meaning that if you end up with a bad config on your server, you need to manually remove it. Either changing the default behavior or adding a flag to not restart nginx would be nice.

**Comment by tas50** [comment]
Thanks for opening this issue. Just today we merged the changes from the chef_nginx fork of this cookbook back to master here. It’s a pretty huge change set and includes over a year of active development that resulted in several major releases. I think there’s a very high chance that this issue has been resolved with that work and at this point I’m going to close this issue out. I’d encourage you to checkout the master branch and please open this issue back up if you’re still having the problem there.

Here’s the changes that were just merged in: https://github.com/chef-cookbooks/nginx/pull/435
