### ISSUE TITLE
Better support for debian upstart

### ISSUE THREAD

**Issue by wesleung** [chef-cookbooks/nginx#411]
Doesn't seem to support upstart init
Problem is nginx initially gets started via upstart and cookbook tries to restart via /etc/init.d/nginx and fails
Current workaround is to login to server and issue `sudo stop nginx;sudo /etc/init.d/nginx start` 

nginx/recipes/default.rb 

```
service 'nginx' do
  supports :status => true, :restart => true, :reload => true
  action   :start
end
```

Missing a line like `provider Chef::Provider::Service::Upstart  if node[:nginx][:init_style]=="upstart"`
Or a case statement would be better

Hoping adding something like the below would resolve the issue 

```
default[:nginx][:init_style]                                                = "upstart"
```

**Comment by iennae** [comment]
Can you check the current version of the cookbook? There have been a number of releases since your original issue was filed. Thanks!

**Comment by wesleung** [comment]
We already switched to chef_nginx as this cookbook said it was deprecated.  Today it says chef_nginx is deprecated and nginx is the proper one again.  Need to switch back again to this cookbook when I find time.  Feel free to close this ticket as the switch will not happen for a few months.

**Comment by iennae** [comment]
If chef_nginx works for you then this cookbook will now work for you as we've ported the changes from chef_nginx to this cookbook. Thanks for responding!
