### ISSUE TITLE
v2.7.6 passenger module and nginx.conf issue

### ISSUE THREAD

**Issue by dedicatted** [chef-cookbooks/nginx#420]
here is my conf:

``` javascript
    "nginx": {
      "repo_source" : "passenger",
      "package_name" : "nginx-extras",
      "user": "webserver",
      "init_style": "init",
      "source": {
        "modules": [
          "nginx::passenger"
        ],
        "use_existing_user" : true
      },
      "passenger": {
        "install_method" : "package",
        "ruby": "/home/webserver/.rvm/gems/ruby-2.2.2@my_rails/wrappers/ruby"
      }
```

while installation I do see:

```
STDERR: Configuration file '/etc/init.d/nginx'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
```

I've checked out both version of a file, and new version that goes with passenger not correct, it has default user 'user www-data;' directive.

**Comment by mikelax** [comment]
@dedicatted  I ran into the same issue and just solved it this am. I think you need to remove the `source` attribute as you want only the nginx-extras package. What tripped me up was that I had to remove both `['nginx']['install_method']` and `['nginx']['source']`. 

There isn't an actual bug with the cookbook, I think the documentation just needs to be improved in the passenger section of the README.

Here is my config
```ruby
  "nginx" => {
    "init_style" => "upstart",
    "default_site_enabled" => false,
    "version" => "1.10.2",
    "keepalive_timeout" => "301",
    "status" => {
      "port" => "8090"
    },
    "repo_source" => "passenger",
    "package_name" => "nginx-extras",
    "passenger" => {
      "version" => "5.0.30",
      "install_method" => "package"
    }
  }
```

**Comment by tas50** [comment]
Thanks for opening this issue. Just today we merged the changes from the chef_nginx fork of this cookbook back to master here. It’s a pretty huge change set and includes over a year of active development that resulted in several major releases. I think there’s a very high chance that this issue has been resolved with that work and at this point I’m going to close this issue out. I’d encourage you to checkout the master branch and please open this issue back up if you’re still having the problem there.

Here’s the changes that were just merged in: https://github.com/chef-cookbooks/nginx/pull/435
