### ISSUE TITLE
Has this project been abondoned

### ISSUE THREAD

**Issue by polliard-jmfe** [chef-cookbooks/nginx#432]
Just curious since the last update on supermarket was March 18, 2015 and the readme says that a rewrite was in the works but there has been seemingly no updates if this project is dead.  I ask because there are many dependency issues that seem to be getting worse the longer this project remains stale.

Thanks for any updates.

**Comment by CanOfSpam3** [comment]
Check out https://github.com/chef-cookbooks/chef_nginx , it claims to be the replacement

**Comment by polliard-jmfe** [comment]
Unfortunately, that project only supports Centos 5 in the RHEL family.  I may just have to break down and write my own. Trying to avoid doing that.  Thanks for the find though.

**Comment by CanOfSpam3** [comment]
It definitely supports 6 & 7, I just ran test kitchen against it as a drop-in replacement for mtm/2.7 and it converged and passed all of our tests against them.

**Comment by fletchowns** [comment]
@polliard-jmfe yup the `chef_nginx` cookbook definitely supports CentOS/RHEL 6 & 7. Note the plus where it says "CentOS 5+"

**Comment by tas50** [comment]
This cookbook is definetly not abandoned. Mike was kind enough to transfer the cookbook over to the Chef Cookbook Engineering team and we'll merge the chef_nginx changes in and then move forward with moving things to a more resource driven model. Expect a large release soon.
