### ISSUE TITLE
Do a final release which turns this into a wrapper for `chef_nginx`?

### ISSUE THREAD

**Issue by sirosen** [chef-cookbooks/nginx#434]
This cookbook is being replaced by `chef_nginx`.

Would it be possible to get a final release, with a new major version number, which simply converts all or many of the 2.7.x recipes into wrappers for their `chef_nginx` equivalents?
This would simplify the transition from `nginx` to `chef_nginx`, and potentially resolve several outstanding issues.

I'm happy to do the PR if it makes it happen, but want confirmation that this is of interest.

**Comment by tas50** [comment]
We're actually going to be going to opposite direction now that the community cookbook engineering team is managing this cookbook. I'll be merging the changes from chef_nginx back into this cookbook and then we'll eventually deprecate the chef_nginx cookbook.

**Comment by sirosen** [comment]
@tas50, since `chef_nginx` is supposedly a delta on top of this cookbook, do we have a guess as to how hard/easy that's going to be? I'm trying to decide whether to migrate existing stuff depending on this (old, I know!) cookbook to depend on `chef_nginx`, or just wait for the changes to come back here. (Happy to discuss helping out in #sous-chefs too, if you want more hands.)
